[versions]
agp = "8.7.3"
circleprogress = "1.2.1"
compiler = "4.15.1"
core = "12.0.0"
coreSplashscreen = "1.0.1"
dotsindicator = "4.3"
facebookLogin = "12.3.0"
firebaseAppcheckRecaptcha = "16.0.0"
firebaseAppcheckRecaptchaVersion = "17.0.1"
firebaseUiStorage = "8.0.0"
javaxMail = "1.6.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
lifecycleViewmodel = "2.6.2"
lottie = "6.0.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
okhttp = "4.10.0"
playServicesAds = "23.6.0"
playServicesAuth = "21.3.0"
roomRuntime = "2.3.0"
firebaseAuth = "23.1.0"
firebaseFirestore = "25.1.1"
roomRuntimeVersion = "2.5.0"
navigationFragment = "2.8.5"
totp = "1.0.0"
youtubeAndroidPlayerApi = "1.2.2"

[libraries]
circleprogress = { module = "com.github.lzyzsd:circleprogress", version.ref = "circleprogress" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
core = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version.ref = "core" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
facebook-login = { module = "com.facebook.android:facebook-login", version.ref = "facebookLogin" }
firebase-appcheck-debug = { module = "com.google.firebase:firebase-appcheck-debug", version.ref = "firebaseAppcheckRecaptcha" }
firebase-appcheck-recaptcha = { module = "com.google.firebase:firebase-appcheck-recaptcha", version.ref = "firebaseAppcheckRecaptcha" }
firebase-appcheck-recaptcha-v1701 = { module = "com.google.firebase:firebase-appcheck-recaptcha", version.ref = "firebaseAppcheckRecaptchaVersion" }
firebase-ui-storage = { module = "com.firebaseui:firebase-ui-storage", version.ref = "firebaseUiStorage" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "compiler" }
javax-mail = { module = "com.sun.mail:javax.mail", version.ref = "javaxMail" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleViewmodel" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleViewmodel" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
room-runtime-v250 = { module = "androidx.room:room-runtime", version.ref = "roomRuntimeVersion" }
room-testing = { module = "androidx.room:room-testing", version.ref = "roomRuntime" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
totp = { module = "de.taimos:totp", version.ref = "totp" }
youtube-android-player-api = { module = "com.google.android.youtube:youtube-android-player-api", version.ref = "youtubeAndroidPlayerApi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

